# Fail if FILE_PATH does not contain REQUIRED_SUBSTRING (simple substring check)
if(NOT DEFINED FILE_PATH)
  message(FATAL_ERROR "FILE_PATH not provided to check_file_contains.cmake")
endif()
if(NOT DEFINED REQUIRED_SUBSTRING)
  message(FATAL_ERROR "REQUIRED_SUBSTRING not provided to check_file_contains.cmake")
endif()

if(NOT EXISTS "${FILE_PATH}")
  message(FATAL_ERROR "File not found: ${FILE_PATH}")
endif()

file(READ "${FILE_PATH}" FILE_CONTENTS)
string(FIND "${FILE_CONTENTS}" "${REQUIRED_SUBSTRING}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "Substring not found in ${FILE_PATH}: ${REQUIRED_SUBSTRING}")
else()
  message(STATUS "Found substring in ${FILE_PATH}")
endif()
